### PR TITLE
GNOME 47

### PR DESCRIPTION
**Pull request by Rafostar**
Update runtime to 47 which is based on Freedesktop 24.08 with corresponding ffmpeg-full

### CODE REVIEW

**Comment by jangernert** [comment]
thanks for the PR

**Comment by Rafostar** [comment]
Tested with video playback on Intel GPU. Works fine here.

Notable differences with latest runtime:
* Working VAAPI HW accel out of box (lower CPU usage)
* Videos start playback at slightly higher quality (uses GStreamer change from [my PR](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/3894), but value not yet adjustable in Clapper API through)
* Bottom controls seek bar no longer changes shape when there are chapters in video (fixed in GTK4)

**Comment by outusuke** [comment]
This error is preventing the application from running after update

flatpak-spawn: Invalid byte sequence in conversion input
Try "flatpak-spawn --help" for more information.

** (news_flash:2): ERROR **: 18:39:48.218: readPIDFromPeer: Unexpected short read from PID socket

**Comment by jangernert** [comment]
If you also see something like  `(process:2): Gtk-WARNING **: 16:29:54.175: Locale not supported by C Using the fallback 'C' locale.` it is probably this error, which  has  a  workaround: https://gitlab.com/news-flash/news_flash_gtk/-/issues/640

**Comment by outusuke** [comment]
> If you also see something like `(process:2): Gtk-WARNING **: 16:29:54.175: Locale not supported by C Using the fallback 'C' locale.` it is probably this error, which has a workaround: https://gitlab.com/news-flash/news_flash_gtk/-/issues/640

That fixed the problem.

**Pull request merged**
